import ShaderityGraphConverter from './main/ShaderityGraphConverter';
import AbstractNode from './node/AbstractNode';
import ShaderityNode from './node/ShaderityNode';
import {
  ShaderStage,
  ShaderStageEnum,
  SocketType,
  SocketTypeEnum,
  SocketDirection,
  SocketDirectionEnum,
  NodeType,
  NodeTypeEnum,
  SamplerType,
  SamplerTypeEnum,
} from './types/CommonEnum';
import {
  ShaderityObjects,
  ShaderityGraphJson,
  ShaderityGraphNode,
  ShaderGlobalData,
  ShaderFunctionData,
  ShaderFunctions,
  NodeData,
  ShaderityNodeData,
  SamplerInputNodeData,
  SocketData,
  InputSocketData,
  OutputSocketData,
  StandardInputSocketData,
  AttributeInputSocketData,
  ShaderAttributeVarType,
  VaryingInputSocketData,
  ShaderVaryingVarType,
  UniformInputSocketData,
  ShaderUniformVarTypeES3,
  StandardOutputSocketData,
  VaryingOutputSocketData,
  SocketConnectionData,
  ShaderOutputSocketData,
  ShaderPrecisionType,
  SamplerInputSocketData,
  SamplerOutputSocketData,
} from './types/CommonType';

export default {
  AbstractNode,
  ShaderityNode,
  ShaderStage,
  SocketDirection,
  ShaderityGraphConverter,
  SocketType,
  NodeType,
  SamplerType,
  Version: ShaderityGraphConverter.shaderityGraphJsonVersion,
};

export type {
  ShaderStageEnum,
  ShaderityObjects,
  ShaderityGraphJson,
  ShaderityGraphNode,
  SocketTypeEnum,
  NodeTypeEnum,
  SamplerTypeEnum,
  SocketDirectionEnum,
  ShaderGlobalData,
  ShaderFunctionData,
  ShaderFunctions,
  NodeData,
  ShaderityNodeData,
  SamplerInputNodeData,
  SocketData,
  InputSocketData,
  OutputSocketData,
  StandardInputSocketData,
  AttributeInputSocketData,
  ShaderAttributeVarType,
  VaryingInputSocketData,
  ShaderVaryingVarType,
  UniformInputSocketData,
  ShaderUniformVarTypeES3,
  StandardOutputSocketData,
  VaryingOutputSocketData,
  SocketConnectionData,
  ShaderOutputSocketData,
  ShaderPrecisionType,
  SamplerInputSocketData,
  SamplerOutputSocketData,
};
