import ShaderityGraphConverter from './main/ShaderityGraphConverter';
import Node from './node/Node';
import {
  ShaderStage,
  ShaderStageEnum,
  SocketType,
  SocketTypeEnum,
  SocketDirection,
  SocketDirectionEnum,
} from './types/CommonEnum';
import {
  ShaderityObjects,
  ShaderityGraphJson,
  ShaderityGraphNode,
  ShaderGlobalData,
  ShaderFunctionData,
  ShaderFunctions,
  NodeData,
  SocketData,
  StandardInputSocketData,
  AttributeInputSocketData,
  ShaderAttributeVarType,
  VaryingInputSocketData,
  ShaderVaryingVarType,
  UniformInputSocketData,
  ShaderUniformVarTypeES3,
  StandardOutputSocketData,
  VaryingOutputSocketData,
  SocketConnectionData,
  ShaderOutputSocketData,
  ShaderPrecisionType,
} from './types/CommonType';

export default {
  Node,
  ShaderStage,
  SocketDirection,
  ShaderityGraphConverter,
  SocketType,
  Version: ShaderityGraphConverter.shaderityGraphVersion,
};

export type {
  ShaderStageEnum,
  ShaderityObjects,
  ShaderityGraphJson,
  ShaderityGraphNode,
  SocketTypeEnum,
  SocketDirectionEnum,
  ShaderGlobalData,
  ShaderFunctionData,
  ShaderFunctions,
  NodeData,
  SocketData,
  StandardInputSocketData,
  AttributeInputSocketData,
  ShaderAttributeVarType,
  VaryingInputSocketData,
  ShaderVaryingVarType,
  UniformInputSocketData,
  ShaderUniformVarTypeES3,
  StandardOutputSocketData,
  VaryingOutputSocketData,
  SocketConnectionData,
  ShaderOutputSocketData,
  ShaderPrecisionType,
};
